# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Introspective
title_long: Always stuck in my head
email: nader@naders.page
description: >- # this means to ignore newlines until "baseurl:"
  This is a site where I explore my technical ideas related
  to coding or leading, interesting thoughts related to 
  my constant goal of self-awareness, and general curiosities
  of life in general.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://naders.page" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username:  weblue

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
paginate: 10

words_read_per_minute: 180

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - README.md
  - .git/
  - LICENSE
  - .github/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - CNAME
  - ignore-*